//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Category
    {
        public Category()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "The field Name is required")]        
        public string Name { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
